### ISSUE TITLE
Error: ${USERID?} missing in Linux

### ISSUE THREAD

**Issue by anarkrypto** [aave/lens-protocol#82] opened 2022-03-27 10:36 UTC
Error with docker-compose right after pulling the repo

> ERROR: Missing mandatory value for "user" option interpolating ${USERID?}:${USERID?} in service "contracts-env": USERID

Command: `docker-compose up`
Or: `sudo docker-compose up`

- Ubuntu 20.04.3 LTS
- Docker version 20.10.10

In fact this variable does not exist in my system.

**Comment by nicolaerusan** [comment] 2022-03-27 21:56
I encountered the same issue on OS X:

`ERROR: Missing mandatory value for "user" option interpolating ${USERID?}:${USERID?} in service "contracts-env": USERID`

Docker Version: 20.10.5
OS X: Big Sur 11.6.4

**Comment by nicolaerusan** [comment] 2022-03-28 00:55
Duplicate of #73 

@anarkrypto I see in another issue thread that the setup has changed from what's on the docs site and we should use the Readme in the Github instead.

**Comment by donosonaumczuk** [comment] 2022-03-28 11:31
Exactly, you should follow the instructions at the repo's README. If you look at the running command it firstly sets the `$USERID` variable to `$UID`.

Closing this. Thanks @nicolaerusan for your help!

**Closed by donosonaumczuk** 2022-03-28 11:31 UTC

**Comment by dabit3** [comment] 2022-05-20 22:57
This worked for me:

```sh
export USERID=1000 && docker-compose build && docker-compose run --name lens contracts-env bash
```
